### ISSUE TITLE
[solved] blacklist.sh stops in " grep -q 'Chain blocklists' "

### ISSUE THREAD

**Issue by rafamerino** [kravietz/blacklist-scripts#2]
Hi, 

I'm trying to setup yout script in my VPS, but when I test it with # sh blacklist.sh, doesn't pass this line: 

```
+ COMPRESS_OPT=--compressed
+ INPUT=INPUT
+ FORWARD=FORWARD
+ iptables -L
+ grep -q 'Chain blocklists' --> (stuck here)
```

(debug thanks to "set -x")

I've installed curl and ipset, as the info says. What's the problem?
OS: Debian 8.3

**Comment by kravietz** [comment]
Try `iptables -L` and see if it returns any output. If you have any unique IPs in the rules, it might get stuck for a while on trying to resolve them in DNS. I have just updated all the -L rules to also include -n flag which prevents the reverse DNS resolution.

**Comment by rafamerino** [comment]
**Solved!**

Yes, I had several IP blocks in my rules, that's why iptables was taking so long in your script. 
Thank you, Pawel :+1:
