### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by guymarc** [kravietz/blacklist-scripts#4]
I installed it on LEDE Reboot (17.01.4, r3560-79f57e422d)
Awesome, Thanks a lot
I think I will install it on my debian server

It should be said somewhere that in order to log, the "log" parameter must be given on the command line
It looks like the $PORTS parameter is never used and all the traffic from the blacklist IPs is dropped

Guy

**Comment by kravietz** [comment]
Thank you, I've added `log` to documentation and removed `PORTS` until is actually implemented :)
