### ISSUE TITLE
LEDE/Openwrt problem on boot

### ISSUE THREAD

**Issue by guymarc** [kravietz/blacklist-scripts#5]
Hello,

On LEDE/OpenWrt the sript is intended to be installed in /etc/firewall.user
The problem is that on boot, the openwrt firewall is loaded BEFORE the network comes up, and this is what we want.
So the script "fails", being unable to download the blacklists.

I chose to keep the script in /etc/firewall.user, but I added a service loading the rules when the network is up.

`#!/bin/sh /etc/rc.common

START=30

COMMAND="sh /etc/firewall.user"

boot() {
        $COMMAND
}
`

Guy

**Comment by kravietz** [comment]
Thanks, I haven't realized that it works like this in LEDE. I actually have one OpenWRT and one LEDE router, and this explains why after reboot the blacklist hasn't come up. I have just added this to documentation.
